name: Build, test and deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        java: [8, 11.0.5]
    name: Java ${{ matrix.java }}
    env:
      CC_TEST_REPORTER_ID: 47b239597faea3da257baa211d7438ff8ba9047319a2c687110f4f8e41bb07f1
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven 
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      id: mvnInstall
    - name: Run tests
      run: mvn test -B
      id: mvnTest
    - name: Record coverage
      run: |
        mvn cobertura:cobertura
      if: startsWith(matrix.java, 11)
    - name: Report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(matrix.java, 11)
#    - name: Deploy to Github packages
#      env:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        packagesUrl: https://maven.pkg.github.com/zapodot
#      run: |
#        mvn deploy -Dregistry=$packagesUrl -Dtoken=$token
#      id: deployGithubPackages
#      if: startsWith(matrix.java, 11)

