name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        java: [8, 11.0.5]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven 
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      id: mvnInstall
    - name: Run tests
      run: mvn test -B
      id: mvnTest
    - name: Coverage
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -B -DrepoToken=$token jacoco:report coveralls:report
      if: startsWith(matrix.java, 11)

#    - name: Deploy to Github packages
#      env:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        packagesUrl: https://maven.pkg.github.com/zapodot
#      run: |
#        mvn deploy -Dregistry=$packagesUrl -Dtoken=$token
#      id: deployGithubPackages
#      if: startsWith(matrix.java, 11)

